### ISSUE TITLE
Problem in reading PySacio in Python 3.3.7 Anaconda

### ISSUE THREAD

**Issue by ghost** [emolch/pysacio#1]
Traceback (most recent call last):

  File "******\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-4-1392a9e678c1>", line 1, in <module>
    import pysacio.py

  File "******\\Anaconda3\lib\site-packages\pysacio.py", line 188
    except SacError, e:
                   ^
SyntaxError: invalid syntax

**Comment by emolch** [comment]
Hi HAMAMA-SAN,

please use this more evolved module of sacio.py: https://github.com/pyrocko/pyrocko/blob/master/src/io/sac.py

Best regards
Sebastian

**Comment by ghost** [comment]
Thanks a lot emolsh.
I will try it.
